name: campus_bit_app
description: "A new Flutter project."

publish_to: "none" # No publicar a pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Ajustando para mayor compatibilidad con plugins

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.2.0+3 # Asegúrate de tener la última versión compatible
  path: ^1.8.3 # Dependencia necesaria para manejar rutas del sistema de archivos
  provider: ^6.0.3 # Agregando provider para manejar el estado (opcional)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Cambiado a una versión más estable y compatible

flutter:
  uses-material-design: true

  assets:
    - assets/uss_logo.png
    - assets/otros.png
    - assets/qr_code.png
    - assets/trasbank.png
    - assets/webpay.png
    - assets/MercadoLibre.png
